# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  encoding: utf8mb4
  timeout: 5000

development:
  <<: *default
  host: 127.0.0.1
  database: suzuki_test_dev
  username: root
  # password: 

test:
  <<: *default
  host: 127.0.0.1
  database: suzuki_test_test
  encoding: utf8
  collation: utf8_general_ci
  encoding: utf8
  username: root
  # password: root

production:
  <<: *default
  database: suzuki_test
  username: <%= ENV['DB_ID'] %>
  password: <%= ENV['DB_PASS'] %
  socket: <%= ENV['DB_SOCKET']
