entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby
service: suzuki-api

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

includes:
- secret.yaml
